# Generated by Django 2.0 on 2021-01-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210127_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='obs_report',
            field=models.TextField(default=1, max_length=400, verbose_name='Descrição do Relátorio'),
            preserve_default=False,
        ),
    ]
