# Generated by Django 2.0 on 2021-01-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_report_obs_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="description_report",
            field=models.CharField(max_length=65, verbose_name="Relatório"),
        ),
    ]
